# Generated by Django 3.2.18 on 2023-04-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='create_data',
            new_name='create_date',
        ),
    ]
