# Generated by Django 3.2.18 on 2023-04-12 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='account',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='账户余额'),
        ),
    ]
