# Generated by Django 3.2.18 on 2023-04-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20230412_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='modification_time',
            field=models.DateTimeField(null=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=32, verbose_name='商品名称'),
        ),
    ]
