# Generated by Django 3.2.18 on 2023-04-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_order_modification_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='modification_people',
            field=models.CharField(max_length=16, null=True, verbose_name='修改人'),
        ),
    ]
